# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)/webcontent/'
    includeRootFolder: false

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo ''$(build.sourcesDirectory)'''
- task: PublishBuildArtifacts@1